const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const src=fs.readFileSync(path.join(__dirname,'../postoscredenciados-covreecia/app.js'),'utf8');
const block=(a,b)=>src.slice(src.indexOf(a),src.indexOf(b,src.indexOf(a)));
function setup(memory,impl){let calls=[],stops=0;const stream={getTracks:()=>[{stop(){stops++;}}],getVideoTracks:()=>[{getSettings:()=>({width:1280,height:960})}]};const c=vm.createContext({receiptCameraRequestVersion:0,activeReceiptCameraStream:null,stopReceiptCameraStream(){},navigator:{deviceMemory:memory,mediaDevices:{async getUserMedia(options){calls.push(options);return impl?impl(options,stream):stream;}}}});vm.runInContext(block('async function requestReceiptCameraStream(', 'async function attachReceiptCameraStream('),c);return{c,calls,stream,stops:()=>stops};}
for(const memory of [undefined,1,2,4])test(`low memory ${memory}: bounded capture without audio`,async()=>{const h=setup(memory);await h.c.requestReceiptCameraStream();assert.equal(h.calls[0].video.width.max,1280);assert.equal(h.calls[0].video.height.max,1280);assert.equal(h.calls[0].video.frameRate.max,15);assert.equal(h.calls[0].audio,false);});
test('facing-mode fallback keeps resolution ceiling',async()=>{let attempt=0;const h=setup(2,(_,s)=>{if(!attempt++)throw Error('camera');return s;});await h.c.requestReceiptCameraStream();assert.equal(h.calls.length,2);assert.equal(h.calls[1].video.width.max,1280);});
test('permission denial does not request twice',async()=>{const h=setup(2,()=>{throw Object.assign(Error('denied'),{name:'NotAllowedError'});});await assert.rejects(h.c.requestReceiptCameraStream());assert.equal(h.calls.length,1);});
test('closing before permission resolves releases late stream',async()=>{let resolve;const h=setup(2,()=>new Promise(r=>resolve=r));const p=h.c.requestReceiptCameraStream();h.c.receiptCameraRequestVersion++;resolve(h.stream);await assert.rejects(p);assert.equal(h.stops(),1);assert.equal(h.c.activeReceiptCameraStream,null);});
test('camera ignoring size constraints stops before preview',async()=>{const h=setup(2,(_,s)=>{s.getVideoTracks=()=>[{getSettings:()=>({width:4000,height:3000})}];return s;});await assert.rejects(h.c.requestReceiptCameraStream());assert.equal(h.stops(),1);});
test('capture blocks double taps and releases on errors',async()=>{let resolve,count=0;const c=vm.createContext({receiptCameraCaptureBusy:false,receiptCameraRequestVersion:1,captureReceiptCameraFrame:()=>{count++;return new Promise(r=>resolve=r);},showErrorMessage(){}});vm.runInContext(block('async function captureReceiptCamera()', 'async function captureReceiptCameraFrame('),c);const a=c.captureReceiptCamera();await c.captureReceiptCamera();assert.equal(count,1);resolve();await a;assert.equal(c.receiptCameraCaptureBusy,false);});
test('camera path keeps JPEG bounded and cached; no full photo decode',()=>{const code=block('async function captureReceiptCameraFrame(', 'async function retakeReceiptCamera(');assert.match(code,/COMPRESSED_RECEIPT_MAX_SIZE/);assert.match(code,/optimizedReceiptFiles.add\(file\)/);assert.match(code,/canvas.width = 1/);assert.match(code,/requestVersion !== receiptCameraRequestVersion/);assert.doesNotMatch(code,/loadImageFromFile|createImageBitmap|readAsDataURL/);});
