const {test}=require('node:test');
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const src=fs.readFileSync(path.join(__dirname,'../wefrotas/wefrotas.js'),'utf8');
function block(name){const start=src.indexOf(`    function ${name}(`);assert.ok(start>=0,name);const tail=src.slice(start+8).search(/\n    (?:async )?function /);return src.slice(start,start+8+tail);}
const context=()=>{const c=vm.createContext({allFinanceEntries:[],allOrders:[],formatDate:x=>x,isFuelEntry:e=>e.entryType==='combustivel',getFinanceEntryDate:e=>e.dataAbastecimento||''});for(const n of ['getEntryVehicleId','getFuelEntriesForVehicle','validateFuelMileageForVehicle','getFuelMileageAudit','translateOnlineAuthError'])vm.runInContext(block(n),c);return c;};
const fuel=(id,date,km,vehicleId='a')=>({id,entryType:'combustivel',dataAbastecimento:date,km,vehicleId});
for(const message of ['Invalid login credentials','Invalid credentials','invalid_credentials'])test(`Portuguese credentials: ${message}`,()=>assert.match(context().translateOnlineAuthError({message}),/E-mail ou senha incorretos/));
for(const [message,pattern] of [['Email not confirmed',/Confirme/],['Failed to fetch',/internet/],['request timeout',/demorou/],['unexpected upstream response',/Não foi possível/]])test(`Portuguese error: ${message}`,()=>assert.match(context().translateOnlineAuthError({message}),pattern));
test('login has no artificial completion delay',()=>{const start=src.indexOf('    async function finishOnlineAuthChecking('),end=src.indexOf('    function toggleOnlineLogin',start);assert.doesNotMatch(src.slice(start,end),/setTimeout|380/);});
for(const km of ['',null,undefined,' ',NaN,Infinity,-1,1.5])test(`reject invalid KM ${km}`,()=>assert.ok(context().validateFuelMileageForVehicle({vehicleId:'a',date:'2026-10-02',km})));
test('zero is a valid odometer for a new vehicle',()=>assert.equal(context().validateFuelMileageForVehicle({vehicleId:'a',date:'2026-10-02',km:0}),''));
test('prior/future bounds, edit exclusion and separate vehicles',()=>{const c=context();c.allFinanceEntries=[fuel('prior','2026-10-01',1000),fuel('future','2026-10-03',1200),fuel('other','2026-10-01',999999,'b')];for(const [km,valid] of [[999,false],[1000,true],[1100,true],[1201,false]])assert.equal(!c.validateFuelMileageForVehicle({vehicleId:'a',date:'2026-10-02',km}),valid);assert.equal(c.validateFuelMileageForVehicle({vehicleId:'a',date:'2026-10-01',km:900,excludeId:'prior'}),'');});
test('same-day backdated entry does not invent intra-day order',()=>{const c=context();c.allFinanceEntries=[fuel('later','2026-10-02',1100)];assert.equal(c.validateFuelMileageForVehicle({vehicleId:'a',date:'2026-10-02',km:1000}),'');});
test('audit identifies vehicle and both records, including grouped children; does not mutate',()=>{const c=context();c.allFinanceEntries=[fuel('prior','2026-09-01',2000),{...fuel('bad','2026-10-01',1000),groupedIntoId:'g'},fuel('other','2026-10-01',500,'b')];const before=JSON.stringify(c.allFinanceEntries);const rows=c.getFuelMileageAudit();assert.equal(rows[1].previous.entry.id,'prior');assert.equal(rows[1].vehicleId,'a');assert.match(rows[1].flags.join(),/menor/);assert.equal(rows[2].flags.length,0);assert.equal(JSON.stringify(c.allFinanceEntries),before);});
test('legacy start/end and missing km are explicit',()=>{const c=context();c.allFinanceEntries=[{...fuel('bad','2026-10-01',''),kmInicial:100,kmFinal:90}];assert.match(c.getFuelMileageAudit()[0].flags.join(),/KM final menor/);});
test('direct Central approval and persistence both validate KM',()=>{for(const [a,b] of [['async function approveCentralPendingRecord','async function notifyCentralRecordRejection'],['async function persistFinanceFormEntry','async function approveCentralPendingRecord']])assert.match(src.slice(src.indexOf(a),src.indexOf(b)),/validateFuelMileageForVehicle/);});
const picker=fs.readFileSync(path.join(__dirname,'../wefrotas/wefrotas-date-picker.js'),'utf8');
const p=vm.createContext({window:{},document:{readyState:'loading',addEventListener(){}}});vm.runInContext(picker,p);
for(const [value,result] of [['29/02/2024','2024-02-29'],['29/02/2026',null],['31/04/2026',null],['07/10/2026','2026-10-07'],['2026-10-07','2026-10-07'],['01/13/2026',null],['foo',null]])test(`typed calendar ${value}`,()=>assert.equal(p.window.WeFrotasDatePicker.parseTypedDate(value,'date'),result));
