const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const src=fs.readFileSync(path.join(__dirname,'../wefrotas/wefrotas.js'),'utf8');
function fn(n){const s=src.indexOf('    function '+n+'('),end=src.slice(s+8).search(/\n    (?:async )?function /);return src.slice(s,s+8+end);}
function setup(){const c=vm.createContext({allVehicles:[{id:'v',placa:'TEST',locado:true}],allDrivers:[],allOrders:[],allFinanceEntries:[],isEntityActive:d=>d.ativo!==false,buildReportData:()=>({}),getReportTitleByType:()=>'',getReportFilters:()=>({}),getFilteredReportOrders:()=>[],getReportDateContextLabel:()=>'',document:{addEventListener(){}},getReportPeriodLabel:()=>'',getReportVehicleLabel:id=>id,formatDate:x=>x,formatCurrency:x=>String(x),getReportFinanceEntries:()=>[],parseDecimalInputValue:x=>Number(x),getFinanceEntryDate:e=>e.dataAbastecimento||e.dataVencimento,isDateWithinRange:(d,s,e)=>(!s||d>=s)&&(!e||d<=e),getEntryImmediateVehicleId:e=>e.vehicleId||c.allOrders.find(o=>o.id===e.orderId)?.vehicleId||'',isFuelEntry:e=>e.entryType==='combustivel',isFuelGroupEntry:e=>e.entryType==='combustivel_agrupado',getFinanceNetTotal:e=>e.kind==='receita'?-e.total:e.total});for(const n of ['getDriverVehicleIds','getVehicleLinkedDrivers','getBatchVehicleDriverId'])vm.runInContext(fn(n),c);vm.runInContext(fs.readFileSync(path.join(__dirname,'../wefrotas/wefrotas-reports-v2.js'),'utf8'),c);return c;}
test('batch resolves canonical driver list without stale vehicle field',()=>{const c=setup();c.allDrivers=[{id:'d',vehicleIds:['v']}];assert.equal(c.getBatchVehicleDriverId(c.allVehicles[0]),'d');});
test('explicit unlink never resurrects legacy vehicle linkage',()=>{const c=setup();c.allVehicles[0].motoristaId='d';c.allDrivers=[{id:'d',vehicleIds:[]}];assert.equal(c.getBatchVehicleDriverId(c.allVehicles[0]),'');});
test('legacy link supported, inactive excluded, ambiguous rejected',()=>{const c=setup();c.allVehicles[0].motoristaId='d';c.allDrivers=[{id:'d'}];assert.equal(c.getBatchVehicleDriverId(c.allVehicles[0]),'d');c.allDrivers[0].ativo=false;assert.equal(c.getBatchVehicleDriverId(c.allVehicles[0]),'');c.allDrivers=[{id:'d',vehicleIds:['v']},{id:'d2',vehicleIds:['v']}];assert.throws(()=>c.getBatchVehicleDriverId(c.allVehicles[0]),/mais de um/);});
test('rental flag is edited and included in both save payloads',()=>{assert.match(src,/vehicle-rented.*type="checkbox"/);assert.match(src,/checked = vehicle.locado === true/);assert.equal((src.match(/motoristaId, locado, chassi/g)||[]).length,2);});
const fuel=(id,date,km,total=100)=>({id,vehicleId:'v',entryType:'combustivel',dataAbastecimento:date,km,litros:20,total});
test('details include services, fuel and OS-linked expenses, exclude income and other vehicle',()=>{const c=setup();c.allOrders=[{id:'o',vehicleId:'v',numero:'123'}];c.allFinanceEntries=[fuel('f','2026-10-01',100),{id:'s',orderId:'o',total:50,dataVencimento:'2026-10-02'},{...fuel('other','2026-10-01',100),vehicleId:'x'},{...fuel('income','2026-10-01',100),kind:'receita'}];const r=c.buildReportData({type:'vehicle_expenses',vehicleId:'v'});assert.equal(r.rows.length,2);assert.equal(r.summary[0].value,'150');assert.equal(r.rows[1].cells[6].text,'123');});
test('group children replace parent; final discount allocated without duplication',()=>{const c=setup();c.allFinanceEntries=[{...fuel('a','2026-10-01',100),groupedIntoId:'g'},{...fuel('b','2026-10-02',200),groupedIntoId:'g'},{id:'g',entryType:'combustivel_agrupado',vehicleId:'v',total:180}];const r=c.buildReportData({type:'vehicle_expenses',vehicleId:'v'});assert.equal(r.rows.length,2);assert.equal(r.summary[0].value,'180');assert.equal(r.rows[0].cells[7].text,'90');});
test('indicators calculate observed distance, costs and estimated interval consumption',()=>{const c=setup();c.allFinanceEntries=[fuel('a','2026-10-01',1000),fuel('b','2026-10-02',1200),{id:'s',vehicleId:'v',total:100,dataVencimento:'2026-10-02'}];const row=c.buildReportData({type:'vehicle_indicators'}).rows[0].cells;assert.equal(row[2].text,'300');assert.equal(row[5].text,'200');assert.equal(row[6].text,'1.5');assert.equal(row[7].text,'10');});
for(const km of [900,'',null])test(`invalid or regressive reading suppresses indicators: ${km}`,()=>{const c=setup();c.allFinanceEntries=[fuel('a','2026-10-01',1000),fuel('b','2026-10-02',km)];assert.equal(c.buildReportData({type:'vehicle_indicators'}).rows[0].cells[6].text,'Sem base suficiente');});
test('date and vehicle filter; source remains unchanged',()=>{const c=setup();c.allFinanceEntries=[fuel('a','2026-09-01',1000),fuel('b','2026-10-01',1200)];const before=JSON.stringify(c.allFinanceEntries);assert.equal(c.buildReportData({type:'vehicle_expenses',start:'2026-10-01',end:'2026-10-31'}).rows.length,1);assert.equal(JSON.stringify(c.allFinanceEntries),before);});
test('multi-vehicle group allocation preserves cents before filtering',()=>{const c=setup();c.allFinanceEntries=[{...fuel('a','2026-10-01',100,1),groupedIntoId:'g'},{...fuel('b','2026-10-01',100,1),vehicleId:'x',groupedIntoId:'g'},{id:'g',total:1.01}];assert.equal(c.buildReportData({type:'vehicle_expenses'}).summary[0].value,'1.01');assert.equal(c.buildReportData({type:'vehicle_expenses',vehicleId:'v'}).summary[0].value,'0.51');});
