const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../wefrotas/wefrotas.js'),'utf8');
function fn(name){const start=source.search(new RegExp('    (?:async )?function '+name+'\\('));assert.ok(start>=0);const tail=source.slice(start+8).search(/\n    (?:async )?function /);return source.slice(start,start+8+tail).split('    window.renewOnlineSession')[0];}
function harness(){let time=1000000,user={id:'a'},locked=false,logout=0;const storage=new Map(),nodes=new Map();
const node=()=>({textContent:'',setAttribute(){},removeAttribute(){},focus(){},remove(){nodes.delete('online-idle-warning');}});
for(const id of ['online-session-clock','online-session-controls','online-session-renew','online-idle-countdown'])nodes.set(id,node());
const c=vm.createContext({Date:{now:()=>time},console,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},document:{body:{classList:{contains:()=>locked},insertAdjacentHTML(){nodes.set('online-idle-warning',node());}},getElementById:id=>nodes.get(id),querySelector:()=>node()},window:{clearTimeout(){},setTimeout(){return 1},WeFrotasBackend:{getUser:()=>user}},toggleOnlinePlatformLoading(){},waitForOnlineLogout:async()=>{logout++},toggleOnlineLogin(){locked=true}});
vm.runInContext("const ONLINE_IDLE_TIMEOUT_MS=300000,ONLINE_SESSION_DURATION_MS=600000,ONLINE_IDLE_WARNING_MS=30000,ONLINE_LAST_ACTIVITY_STORAGE_KEY='wefrotas_online_last_activity_v1';let onlineIdleTimer=null,onlineActivityMemory=0,onlineSessionDeadline=0,onlineWarningOpen=false,onlineLogoutInProgress=false;",c);
for(const name of ['stopOnlineIdleTimer','onlineSessionStorageKey','readOnlineLastActivityAt','markOnlineActivity','scheduleOnlineIdleLogout','renewOnlineSession','updateOnlineSessionClock','expireOnlineSessionByInactivity'])vm.runInContext(fn(name),c);
return {c,nodes,storage,advance:ms=>time+=ms,logout:()=>logout,setUser:u=>user=u};}
test('starts at ten minutes; warning after five, not before',()=>{const h=harness();h.c.scheduleOnlineIdleLogout();assert.equal(h.nodes.get('online-session-clock').textContent,'10:00');h.advance(299000);h.c.updateOnlineSessionClock();assert.equal(h.nodes.has('online-idle-warning'),false);h.advance(1000);h.c.updateOnlineSessionClock();assert.equal(h.nodes.get('online-idle-countdown').textContent,'30');assert.ok(h.nodes.has('online-idle-warning'));});
test('manual renewal clears warning and resets countdown',()=>{const h=harness();h.c.scheduleOnlineIdleLogout();h.advance(310000);h.c.updateOnlineSessionClock();assert.equal(h.nodes.get('online-idle-countdown').textContent,'20');h.c.renewOnlineSession();assert.equal(h.nodes.has('online-idle-warning'),false);assert.equal(h.nodes.get('online-session-clock').textContent,'10:00');});
test('unanswered warning logs out once after 30 seconds',async()=>{const h=harness();h.c.scheduleOnlineIdleLogout();h.advance(330000);h.c.updateOnlineSessionClock();await h.c.expireOnlineSessionByInactivity();assert.equal(h.logout(),1);});
test('continued use renews ten-minute lease automatically',()=>{const h=harness();h.c.scheduleOnlineIdleLogout();for(let i=0;i<6;i++){h.advance(100000);h.c.markOnlineActivity();h.c.updateOnlineSessionClock();}assert.equal(h.nodes.get('online-session-clock').textContent,'10:00');assert.equal(h.logout(),0);});
test('activity from same-user tab prevents idle logout',()=>{const h=harness();h.c.scheduleOnlineIdleLogout();h.advance(310000);h.storage.set(h.c.onlineSessionStorageKey(),String(1310000));h.c.updateOnlineSessionClock();assert.equal(h.nodes.has('online-idle-warning'),false);assert.equal(h.logout(),0);});
test('different users have isolated activity keys',()=>{const h=harness();const first=h.c.onlineSessionStorageKey();h.setUser({id:'b'});assert.notEqual(h.c.onlineSessionStorageKey(),first);});
test('background/suspended clock uses timestamps, not number of timer ticks',()=>{const h=harness();h.c.scheduleOnlineIdleLogout();h.advance(900000);h.c.updateOnlineSessionClock();assert.equal(h.logout(),1);});
