const {test}=require('node:test');
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const src=fs.readFileSync(path.join(__dirname,'../wefrotas/wefrotas.js'),'utf8');
function setup(){
 const c=vm.createContext({allVehicles:[{id:'a'},{id:'b'}],allOrders:[{id:'os',vehicleId:'a',dataInicio:'2026-09-01'}],allFinanceEntries:[],
 normalizeDateForFilter:x=>String(x||'').slice(0,10),isFuelEntry:e=>e.entryType==='combustivel',isFuelGroupEntry:e=>e.entryType==='combustivel_agrupado',
 getFuelGroupChildren:e=>e.children||[],isDateWithinRange:(d,s,e)=>(!s||d>=s)&&(!e||d<=e)});
 for(const [a,b] of [['getFinanceTotal','normalizeFinanceNoteLabel'],['getEntryLinkedOrder','isFinanceEntryInsidePeriod'],['getOrderCompetenceDate','getVehicleDistributedCostTotal'],['getFinanceEntryDate','getFinanceEntryStatus'],['getReportFinanceEntries','getReportMaintenanceItems'],['getVehicleCostStats','getDashboardExpirations'],['getCostPerKmTone','renderMonthlyVehicleCostChart']])vm.runInContext(src.slice(src.indexOf(`    function ${a}(`),src.indexOf(`    function ${b}(`)),c);
 return c;
}
const fuel=(id,km,total=100)=>({id,vehicleId:'a',orderId:'os',entryType:'combustivel',dataAbastecimento:`2026-10-${id==='one'?'01':'10'}`,total,km});
test('vehicle filters include pending direct links and keep company vehicles apart',()=>{const c=setup();c.allFinanceEntries=[{...fuel('one',1000),orderId:''},{...fuel('two',1100),vehicleId:'b',orderId:''}];assert.equal(c.getReportFinanceEntries({type:'overview',vehicleId:'a'}).length,1);});
test('cost and km use same OS competence, even when fuel occurs next month',()=>{const c=setup();c.allFinanceEntries=[fuel('one',1000),fuel('two',1100)];const s=c.getVehicleCostStats({vehicleId:'a',start:'2026-09-01',end:'2026-09-30'})[0];assert.equal(s.totalCost,200);assert.equal(s.totalKm,100);assert.equal(s.costPerKm,2);const next=c.getVehicleCostStats({vehicleId:'a',start:'2026-10-01',end:'2026-10-31'})[0];assert.equal(next.totalCost,0);assert.equal(next.totalKm,0);assert.equal(next.costPerKm,null);});
test('pending unallocated fuel does not inflate distributed KM denominator',()=>{const c=setup();c.allFinanceEntries=[fuel('one',1000),fuel('two',1100),{...fuel('three',9000),orderId:''}];assert.equal(c.getVehicleCostStats({vehicleId:'a'})[0].totalKm,100);});
for(const km of [1000,'',undefined,'bad',-1,900])test(`missing/equal/decreasing/invalid readings have no rate: ${km}`,()=>{const c=setup();c.allFinanceEntries=[fuel('one',1000),fuel('two',km)];const s=c.getVehicleCostStats({vehicleId:'a'})[0];assert.equal(s.costPerKm,null);assert.equal(c.getCostPerKmTone(s.costPerKm),'neutral');});
test('group final cost counted once; children supply readings and inherit parent OS period',()=>{const c=setup();const children=[{...fuel('one',1000),orderId:'',groupedIntoId:'g'},{...fuel('two',1100),orderId:'',groupedIntoId:'g'}];c.allFinanceEntries=[...children,{id:'g',orderId:'os',entryType:'combustivel_agrupado',total:180,children}];const s=c.getVehicleCostStats({vehicleId:'a',start:'2026-09-01',end:'2026-09-30'})[0];assert.equal(s.totalCost,180);assert.equal(s.totalKm,100);assert.equal(s.costPerKm,1.8);});
test('valid vehicles rank before vehicles lacking KM',()=>{const c=setup();c.allOrders.push({id:'b-os',vehicleId:'b',dataInicio:'2026-09-01'});c.allFinanceEntries=[fuel('one',1000),{...fuel('two',1000),vehicleId:'b',orderId:'b-os'},{...fuel('three',1100),vehicleId:'b',orderId:'b-os'}];const s=c.getVehicleCostStats();assert.equal(s[0].vehicleId,'b');assert.equal(s[1].costPerKm,null);});
test('irregularities compare only same vehicle, including entries without OS',()=>{const c=setup();Object.assign(c,{buildReportData:()=>({}),getReportTitleByType:()=>'',getReportFilters:()=>({}),getFilteredReportOrders:()=>[],getReportDateContextLabel:()=>'',document:{addEventListener(){}},getReportPeriodLabel:()=>'',getReportVehicleLabel:id=>id||'Todos',formatDate:x=>x,parseDecimalInputValue:x=>Number(x||0)});vm.runInContext(fs.readFileSync(path.join(__dirname,'../wefrotas/wefrotas-reports-v2.js'),'utf8'),c);c.allFinanceEntries=[{...fuel('one',5000),orderId:'',comprovanteUrl:'test'},{...fuel('two',1000),orderId:'',vehicleId:'b',comprovanteUrl:'test'}];assert.equal(c.buildReportData({type:'irregularities'}).rows.length,0);c.allFinanceEntries.push({...fuel('three',4000),orderId:'',comprovanteUrl:'test'});assert.equal(c.buildReportData({type:'irregularities',vehicleId:'a'}).rows.length,1);});
test('screen, report and print render missing KM explicitly',()=>{assert.equal((src.match(/item.costPerKm === null \? 'Sem base de KM'/g)||[]).length,3);assert.match(src,/vehicleStats.find\(item => item.costPerKm !== null\)/);});
